#!/bin/bash

set -ex

# format code
if [[ $CI ]]; then
    uv run ruff format --check .
else
    uv run ruff format .
fi

# lint (includes import sorting)
uv run ruff check .

# type check code
uv run mypy .
