#!/bin/sh

set -ex

# format code
if [[ $CI ]]; then
    ./.venv/bin/black --check .
    ./.venv/bin/isort --check-only .
else
    ./.venv/bin/black .
    ./.venv/bin/isort .
fi

# type check code
./.venv/bin/mypy .

# lint
./.venv/bin/flake8 codeowners
